# Generated by Django 5.1.2 on 2024-10-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsn_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('hierarchies', models.CharField(max_length=10)),
                ('officename', models.CharField(max_length=255)),
                ('currentRegulations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dataOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsn_users.dataoffice')),
            ],
        ),
    ]
